### ISSUE TITLE
fstab missing rootfs

### ISSUE THREAD

**Issue by hex2a** [grml/grml-debootstrap#100]
When executing:
`grml-debootstrap --target=/dev/md0`, there is no entry for `/` in /etc/fstab.

Versions before this commit work:
https://github.com/grml/grml-debootstrap/commit/622fa874a2ecc04fec77cbb455419f4618112f9e

**Comment by sts** [comment]
@mika have you got an idea on how we could approach to fix this issue?

**Comment by mika** [comment]
@sts I'm currently looking into this to find an acceptable workaround

**Comment by mika** [comment]
I came up with https://github.com/grml/grml-debootstrap/commit/33e46ce40d9877ce4fed236194b22977128223cd which seems to fix the issue both for `--target=/dev/blockdevice` as well as `--target=/mnt/point`.
I'd appreciate if you could acknowledge that this indeed fixes your issue.

**Comment by sts** [comment]
@mika we will give it a try! thanks

**Comment by hex2a** [comment]
The issue is fixed in https://github.com/grml/grml-debootstrap/commit/33e46ce40d9877ce4fed236194b22977128223cd, thanks!

**Comment by mika** [comment]
Reopening, since https://github.com/grml/grml-debootstrap/commit/33e46ce40d9877ce4fed236194b22977128223cd is unmerged yet

**Comment by mika** [comment]
Thanks for reporting + verification, @hex2a! 👍
