### ISSUE TITLE
BOOT_APPEND works only for VMs

### ISSUE THREAD

**Issue by kivoli** [grml/grml-debootstrap#106]
Appending stuff to the Kernel cmdline via `BOOT_APPEND` in the config file or `--bootappend` on the CLI does not work because the responsible code is only executed for virtual machines:

https://github.com/grml/grml-debootstrap/blob/351237a25834610576f953d1be2976f043e6f862/grml-debootstrap#L1278

# Steps to reproduce the problem

1. Prepare physical machine for debootstrap installation
2. Execute `grml-debootstrap` with `--appendboot 'net.ifnames=0 biosdevname=0'`

# Expected behavior

Content of `BOOT_APPEND` appended to `GRUB_CMDLINE_LINUX_DEFAULT` in `/etc/default/grub`.

# Actual behavior

Does not happen.

# Your system configuration

Physical hardware

# Software versions

grml-debootstrap 0.78 (from inside grml 2017.05 Freedatensuppe)

**Comment by suntong** [comment]
+1 -- I'm just about to report the same thing.

grml-debootstrap from latest grml-small, v0.85.

**Comment by mika** [comment]
I started to work on this (completely untested though), so if anyone is interesting in this feature and/or can help us in testing, please take a look at https://github.com/grml/grml-debootstrap/pull/137

**Comment by suntong** [comment]
I tested and can confirm that the issue has been fixed in `grml-debootstrap - version 0.89~bootappend01`

**Comment by mika** [comment]
Thanks for testing this, @suntong - appreciated!
I just submitted this via https://github.com/grml/grml-debootstrap/pull/142

If anyone notices any problems please let us know, thanks!
