### ISSUE TITLE
No network

### ISSUE THREAD

**Issue by suntong** [grml/grml-debootstrap#135]
Found that I don't have eth0 after 1st boot up. 

Is it that I should have used `--defaultinterfaces`?

**Comment by mika** [comment]
`eth0` exists only when booting your system with kernel command line `net.ifnames=0`. So yes, using `--defaultinterfaces` should fix your issue.

I've reported https://github.com/grml/grml-debootstrap/issues/136 to improve the defaults (the tricky part is that under Grml it might be eth0 but Debian doesn't default to net.ifnames=0 and VMs etc might have further surprises.)

PS: please provide more information when reporting issues (e.g. the grml-debootstrap command line you used) so we don't have to guess what you're about about, thanks :)

**Comment by suntong** [comment]
Yep, that works. thx.
