### ISSUE TITLE
Can't ssh into the finished box

### ISSUE THREAD

**Issue by suntong** [grml/grml-debootstrap#139]
ssh into the finished box has been working before, when I'm using the `grml-debootstrap` that comes with the latest `grml-small`, but with

grml-debootstrap version 0.89~bootappend01

I can no longer ssh into the finished box:

```
$ ssh root@10.66.21.106
root@10.66.21.106's password: 
Permission denied, please try again.
root@10.66.21.106's password: 

$ ssh root@10.66.21.106
root@10.66.21.106's password: 
Permission denied, please try again.
root@10.66.21.106's password: 
```

Once again, ssh into the finished box has been working before, even with the latest bullseye release. 

Please double-check.

Here is the full log http://paste.debian.net/1096874/

thx

**Comment by mika** [comment]
ssh logins for user **root** aren't permitted with _password_ due to the default `PermitRootLogin prohibit-password` configuration in sshd_config (this is not grml-debootstrap specific, but default in openssh upstream as well as in Debian), quoting from `sshd_config(5)`:

> If this option is set to prohibit-password or without-password, password and keyboard-interactive authentication are disabled for root.

This behavior is present since Debian stretch.

The grml-debootstrap option `--sshcopyid` supports setting up public keys if you've a key available via `ssh-add -L`.

I agree that this "root login via ssh isn't possible using a password" isn't really beautiful, and we (@jkirk and myself) would like to improve this behavior, though we're not sure whether enabling root logins with passwords by default is really a good choice. :-/ So: to be discussed.

**Comment by suntong** [comment]
> This behavior is present since Debian stretch.

Ah, 

> _"ssh into the finished box has been working before"_

That was ssh into grml-live, and the only time the finished box was up is that it has no `eth0` device. 

OK. I get you. 

But now we have a dilemma, allowing remote access to the box and being secure. We can't have both perfectly in place so I'm thinking some compromise has to be made. 

- First of all, the situation is, when `grml-debootstrap` is used, most probably it is done remotely, to a VM, or to a device within VM. I know this extremely simplified the situation, but it is our target audience. 
- I.e., the likelihood of the newly provisioned system being hacked into is slim. Even it did happen, then the intruder will be facing a bare metal that has just standard Debian. E.g., for my case, I won't loose anything, and the salvation is simple -- redo `grml-debootstrap` again. 
- The point I want to make is that, if there is compromised that need to be made, then I'm willing to compromise on the security side, than being locked out. 
- Because, althoug `-sshcopyid` supports setting up public keys, but for me, using `grml-live`, getting that public key into grml-live is a hurdle that I need to jump through in the first place, and would like to avoid as much as possible. 

So overall, I'd in favor of enabling root logins with passwords, allowing people to get into the box and do further installation/customization etc, without any hassle. Because any other alternatives will have bigger hassle than this. 

Then we can suggest people to close the security gap themselves afterward by, 

- change the root password, and 
- disable root logins with passwords

Again, this is the least hassle approach, and all other alternatives will have bigger hassle. 

If we can't agree on this, then please provide an option for users to do so "on their own risk", :-)

cheers

**Comment by mika** [comment]
Now with having https://github.com/grml/grml-debootstrap/pull/155 just being merged I think we have a solution for this issue with the new `--sshcopyauth` option. I'm therefore closing this hereby, if we missed anything please let us know or open a new issue.
