### ISSUE TITLE
Missing Linux kernel in VM image

### ISSUE THREAD

**Issue by paulmenzel** [grml/grml-debootstrap#146]
Using grml-debootstrap v0.72-118-g6839f3b the command below does not install the Linux kernel.

    grml-debootstrap --vm --vmfile --target /dev/shm/debian-32.img -r sid --arch i386 --filesystem ext4

Same for *buster*.

    grml-debootstrap --vm --vmfile --target /dev/shm/debian-32.img -r buster --arch i386 --filesystem ext4

**Comment by paulmenzel** [comment]
[grml-debootstrap.log](https://github.com/grml/grml-debootstrap/files/3960337/grml-debootstrap.log)

**Comment by mika** [comment]
uhm:

```
I: Base system installed successfully.
 * Preparing chroot system
cp: cannot stat '/etc/debootstrap/chroot-script': No such file or directory
chmod: cannot access '/mnt/debootstrap.3851/bin/chroot-script': No such file or directory
cp: cannot stat '/etc/debootstrap/locale.gen': No such file or directory
tar (child): /etc/debootstrap/devices.tar.gz: Cannot open: No such file or directory
```

I've no idea what's your version `v0.72-118-g6839f3b` supposed to be and what you're using here. We're at version v0.90-1-gef76531 in master and the latest stable version is v0.90 and version v0.72 dates back to 2015.
Feel free to update the issue if you can reproduce the issue with a more recent/official grml-debootstrap version, closing in the meanwhile though.

**Comment by paulmenzel** [comment]
Sorry for the confusion. The upstream repository was not configured, and the git tags were missing. The commit is equal to v0.89-6-g6839f3b.

I retried with v0.90-2-g22cdc9f, and I am able to reproduce the issue.

**Comment by paulmenzel** [comment]
Please re-open.

**Comment by mika** [comment]
I need the runtime log of your installation, I can't reproduce it with your command line and it works perfectly fine for me.

**Comment by paulmenzel** [comment]
Sorry, I didn’t read the error message.

```
I: Base system installed successfully.
 * Preparing chroot system
cp: cannot stat '/etc/debootstrap/chroot-script': No such file or directory
chmod: cannot access '/mnt/debootstrap.24646/bin/chroot-script': No such file or directory
cp: cannot stat '/etc/debootstrap/locale.gen': No such file or directory
```

The `chroot-script` was in the repository directory. So, `-d ~/src/grml-debootstrap/` fixed it for me.
