### ISSUE TITLE
E: Package 'firmware-linux' has no installation candidate

### ISSUE THREAD

**Issue by suntong** [grml/grml-debootstrap#150]
I'm getting:

```
E: Package 'firmware-linux' has no installation candidate
 -> Failed (rc=1)
```

I don't know if it is Debian's problem or `grml-debootstrap`'s. But last time I run `grml-debootstrap` on this same machine (v0.89), it was fine. The host is a VM.

The full log is at: http://paste.debian.net/1127348/, for bullseye.
And for buster: http://paste.debian.net/1127350/

Please help. thx.

**Comment by mika** [comment]
In the bullseye run you have:

```
E: Release file for http://deb.debian.org/debian/dists/bullseye/InRelease is not valid yet (invalid for another 2h 36min 47s). Updates for this repository will not be applied.
E: Release file for http://security.debian.org/debian-security/dists/bullseye-security/InRelease is not valid yet (invalid for another 4h 15min 34s). Updates for this repository will not be applied.
```

In buster:

```
E: Release file for http://security.debian.org/dists/buster/updates/InRelease is not valid yet (invalid for another 4h 6min 20s). Updates for this repository will not be applied.
```

Looks like it was a temporary problem with the Debian repositories, works fine for me as of now.

**Comment by suntong** [comment]
thanks a lot mika, sorry I wasn't sure where the problem was.
