### ISSUE TITLE
Do not umount /proc and /sys, if it they aren't mounted

### ISSUE THREAD

**Issue by fransvanberckel** [grml/grml-debootstrap#156]
@mika A quick hack for if /proc and /sys are not mounted, on top you do ...

[ -r /proc/1 ] || mount -t proc none /proc
[ -r /sys/kernel ] || mount -t sysfs none /sys

So at finalize, umount got to be? ...

[ -r /sys/kernel ] || umount /sys >/dev/null 2>/dev/null || true
[ -r /proc/1 ] || umount /proc >/dev/null 2>/dev/null || true

**Comment by mika** [comment]
@fransvanberckel well, we're just unconditionally un-mounting it, it doesn't do any harm, nor? I'm not objecting against changing this, though we _might_ consider getting rid of the `|| true` as well then.

**Comment by fransvanberckel** [comment]
You're right, this doesn't do any harm.

**Comment by paulmenzel** [comment]
Can you close it?
