### ISSUE TITLE
Provide option to disable colors / escape characters

### ISSUE THREAD

**Issue by mika** [grml/grml-debootstrap#159]
When executing grml-debootstrap within e.g. Jenkins the console output includes the escape characters, like:

```
 [32;01m*[0m grml-debootstrap [0.93] - Please recheck configuration before execution:
```

A customer of mine would like to get those removed, which actually makes sense.

FTR, would be nice to detect that we are not running on an interactive terminal and then automatically disable escape sequences, so we don't need to explicitely disable colors / escape characters.

**Comment by zeha** [comment]
> FTR, would be nice to detect that we are not running on an interactive terminal and then automatically disable escape sequences, so we don't need to explicitely disable colors / escape characters.

I want to point out two things:
1) often the check is on `TERM=dumb` or so
2) not all non-interactive terminals do not support colors. Easier said: Jenkins is one of the non-interactive terminals that cannot do colors, but many popular CI tools do support color.

**Comment by mika** [comment]
Oh interesting, thanks for this information, @zeha! :heart:
