### ISSUE TITLE
fstab: Mount option `errors=remount-ro` results in F2FS root not being mounted as read-writable

### ISSUE THREAD

**Issue by paulmenzel** [grml/grml-debootstrap#163]
Using grrml-debootstrap 0.94, and creating a VM image with a F2FS formatted root partition

    sudo DEBOOTSTRAP=mmdebstrap grml-debootstrap --vmfile --vmsize 2G --target /dev/shm/debian-f2fs.img --filesystem=f2fs --release sid

the root partition cannot be mounted, because the mount option `errors=remount-ro` are unknown.

**Comment by paulmenzel** [comment]
Here is the output:

    # mount -o remount,rw /dev/sda1
    [   94.941005] F2FS-fs (sda1): Unrecognized mount option "errors=remount-ro" or missing value
    mount: /: mount point not mounted or bad option

**Comment by paulmenzel** [comment]
In GRUB, editing the Linux kernel command line, and removing `ro` from it (or replacing it by `rw`), also works around it.

**Comment by mika** [comment]
Linux's `Documentation/filesystems/f2fs.rst` indeed doesn't list `errors` as supported mount option for f2fs, but TBH, I'm also a bit reluctant to add such file system specific workarounds to grml-debootstrap. :-/ What's your use case to use F2FS? (Looking for opinions that might trick me into adding such workarounds ;))
