### ISSUE TITLE
GRUB drops into rescue mode when using F2FS formatted root partition

### ISSUE THREAD

**Issue by paulmenzel** [grml/grml-debootstrap#164]
Using grrml-debootstrap 0.94, and creating a VM image with a F2FS formatted root partition

    $ sudo DEBOOTSTRAP=mmdebstrap grml-debootstrap --vmfile --vmsize 2G --target /dev/shm/debian-f2fs.img --filesystem=f2fs --release sid
    […]
     * Installing Grub as bootloader.
    1+0 records in
    1+0 records out
    440 bytes copied, 6.2596e-05 s, 7.0 MB/s
    50+1 records in
    50+1 records out
    25898 bytes (26 kB, 25 KiB) copied, 0.000127481 s, 203 MB/s
    […]
    $ sudo chown testuser: /dev/shm/debian-f2fs.img

starting the image with QEMU

    $ qemu-system-x86_64 -enable-kvm -cpu host -m 2G -hda debian-f2fs.img

drops into the GRUB rescue shell.

You can work around it, by mounting the image as a loop device

    $ udisksctl loop-setup -f debian-f2fs.img

and copying the Linux kernel and initrd out from `/media/testuser/…/boot/`, and start QEMU with that.

    $ qemu-system-x86_64 -enable-kvm -m 2G -hda debian-f2fs.img -kernel /dev/shm/vmlinuz-5.9.0-5-amd64 -initrd /dev/shm/initrd.img-5.9.0-5-amd64 -append root="/dev/sda1"

After fixing issue https://github.com/grml/grml-debootstrap/issues/163 (also in loop mounted path) to get the root partition mounted, log in as root and run `grub-install /dev/sda`, and it works.

It could be, that the driver is missing in the grub-mkimage command below:

https://github.com/grml/grml-debootstrap/blob/617ed170aa5244120e91669527693e93e21981c7/grml-debootstrap#L1526-L1527

**Comment by paulmenzel** [comment]
Replacing `ext2` by `f2fs` indeed fixes this:

    chroot "${MNTPOINT}" grub-mkimage -O i386-pc -p "(hd0,msdos1)/boot/grub" -o /tmp/core.img biosdisk part_msdos f2fs

**Comment by mika** [comment]
Great debugging, thanks! Let's try to fix this together with https://github.com/grml/grml-debootstrap/issues/163
