### ISSUE TITLE
grml-debootstrap customization starting-point/template repo

### ISSUE THREAD

**Issue by suntong** [grml/grml-debootstrap#170]
UTSL reveals that `grml-debootstrap` depends on many files and folders, 

The ones listed under the `Files` sections, namely,

```
/etc/debootstrap/config
/etc/debootstrap/chroot-script
/etc/debootstrap/locale.gen
/etc/debootstrap/packages
/etc/debootstrap/extrapackages/
```

are only the starting point. 

There are also `/etc/debootstrap/debconf-selections`, and `/etc/debootstrap, /etc/debootstrap/chroot-scripts/ /etc/debootstrap/extrapackages/` etc. 

Would it be nice to collect all of them together and put them into a single customization template repo? 

So for users to do deep `grml-debootstrap` customization, they just need to

- clone the starting-point/template repo,
- make whatever changes that they need, and have those changes version tracked
- by the time then need to do `grml-debootstrap`, they just need to
  * download, say `https://github.com/me/my-grml-debootstrap-cust-repo/archive/refs/heads/main.zip`
  * extract to `/`
  * run `grml-debootstrap` with as minimum command-line parameters as possible.

Running `grml-debootstrap` with as minimum tweaking and command-line parameters as possible is the biggest selling point to me (let alone they can do branching in their own repo), as the only time I need to invoke `grml-debootstrap` is when booting into grml *live*, and when all of my own tools, credentials, and notes, are ***gone***. I cannot do copy and paste, yet typing a super long command-line and parameters will increase the risk of typo. Since parameters to `grml-debootstrap` are so critical, it always make me nervous when doing so.

This way, it has the least demand when people in grml *live*, and will have the least chance to make (unnoticed) mistake, and require the least amount of double-checking over and over...

Please consider. thx

**Comment by mika** [comment]
No objections from my side supporting such a use case, but we have to keep security issues with loading and sourcing "random" files in mind. If someone wants to work on this, feel invited to do so :)

**Comment by mika** [comment]
Closing as agreed by author
