### ISSUE TITLE
Handling of variable `KEYRING` passed to debootstrap

### ISSUE THREAD

**Issue by paulmenzel** [grml/grml-debootstrap#184]
In

https://github.com/grml/grml-debootstrap/blob/0d4c08983c4a940464401fb48ca43afdab7e54d1/grml-debootstrap#L1646

would `KEYRING` need to contain debootstrap’s switch `--keyring`?

From debootstrap(8):

>        --keyring=KEYRING
>               Override  the  default  keyring for the distribution being boot‐
>               strapped, and use KEYRING to check signatures of  retrieved  Re‐
>               lease files.

**Comment by mika** [comment]
The `KEYRING` you stumbled upon is a leftover from commit 06fc8bd266ad5. Removed accordingly, thanks for reporting!
