### ISSUE TITLE
grml-debootstrap --grmlrepos [...]: "GPG error" + "The repository ... is not signed"

### ISSUE THREAD

**Issue by novoid** [grml/grml-debootstrap#187]
Hi,

On grml 2021-07 full amd64 full, the option "--grmlrepos" does not make sure that the OpenPGP pubkey is fetched before trying to install packages. Therefore, the stdout contains warnings and errors related to that.

Command used:

```
grml-debootstrap --arch amd64 --contrib --efi /dev/nvme0n1p1 --grmlrepos --hostname myhostname --mirror https://ftp.tugraz.at/mirror/debian --non-free --target /media/myhostname --password mypassword 
```

**Comment by mika** [comment]
Thanks, could reproduce the behavior and just fixed it :)
