### ISSUE TITLE
EFI Boot problems

### ISSUE THREAD

**Issue by AntonioSun** [grml/grml-debootstrap#195]
I recently done both BIOS and EFI boots using the _**same**_ grml usb and have noticed their behavioral differences. They are maybe related to the EFI Boot or maybe not. What's your related experiences are?

I noticed that if the machine is booted in EFI mode, then

- I don't have IP address for my `eth0` device, and I need to set things up myself manually.
- The HD of my machine is named /dev/nvme0n1px, instead of /dev/sdax

In both cases, no such problem when the machine is booted in BIOS mode. But because they are different machines, so I'm not sure if is more machine related or boot mode related. 

Comments?

**Comment by mika** [comment]
> I don't have IP address for my eth0 device, and I need to set things up myself manually.

We'd need further information to be able to assist here (what does "manually set things up" mean, and what exactly isn't working out of the box that is supposed to be working as such?), though that should not be related to BIOS nor EFI boot, sounds more like a system/environment specific issue.

> The HD of my machine is named /dev/nvme0n1px, instead of /dev/sdax

`/dev/nvme0n1px` means your system uses an NVMe disk, nothing unexpected at all.

FYI: this repository is really only about our software `grml-debootstrap`, for generic issues unrelated to any specific please use
https://github.com/grml/grml/issues instead.
