### ISSUE TITLE
Support for full disk encryption (FDE) with only entering one password (without /boot)?

### ISSUE THREAD

**Issue by paulmenzel** [grml/grml-debootstrap#198]
Has somebody written scripts already to set up a system with full disk encryption, that means no separate `/boot` partition (and unencrypted ESP)? The challenge is to only enter the passphrase once in the “boot loader”. ([*Full disk encryption (including boot) on Debian*](https://www.dwarmstrong.org/fde-debian/) documents one way with Debian 10 (buster) though current GRUB should support LUKS2.)

    # mkdir -m 0700 /etc/keys
    # (umask 0077 && dd if=/dev/urandom bs=1 count=64 of=/etc/keys/root.key conv=excl,fsync)
    # cryptsetup luksAddKey /dev/sda5 /etc/keys/root.key
    # cryptsetup luksDump /dev/sda5

`/etc/cryptsetup` needs to be updated:

    sda5_crypt UUID=... /etc/keys/root.key luks,discard,key-slot=0

    # echo KEYFILE_PATTERN="/etc/keys/*.key" >> /etc/cryptsetup-initramfs/conf-hook
    # echo UMASK=0077 >> /etc/initramfs-tools/initramfs.conf

The boot loader (only GRUB supported by grml-debootstrap) also needs to be adapted.

**Comment by mika** [comment]
I use such a similar[1] system myself, the setup is basically based on what I documented at https://michael-prokop.at/blog/2014/02/28/state-of-the-art-debianwheezy-deployments-with-grub-and-lvmsw-raidcrypto/ + https://michael-prokop.at/blog/2014/02/28/full-crypto-setup-with-grub2/. In its core it's pretty much only:

```
echo GRUB_ENABLE_CRYPTODISK=y >> /etc/default/grub
echo "crypt_rootfs UUID=[...] none luks,discard" >> /etc/crypttab
```

There's not much further to be done to get FDE, including crypted GRUB.

[1] Similar as in: have to enter the crypto password in GRUB once, and then also once for the filesystems (only once for all of them) during boot stage.

**Comment by paulmenzel** [comment]
Thank you for your answer and sorry for me being unclear. Yes, I know of the solution with entering the password twice, but the goal is to only enter it once.

**Comment by mika** [comment]
You want to enter the password only once in GRUB and that should be also used for opening the filesystems during bootup then? If so, I'm not aware how this could work, and it's clearly outside the scope of grml-debootstrap then ;)
