### ISSUE TITLE
Disable new ext4 feature metadata_csum_seed feature for older Debian releases?

### ISSUE THREAD

**Issue by mika** [grml/grml-debootstrap#204]
The annoying `metadata_csum` situation seems to reappear again with `metadata_csum_seed`, see https://bugs.debian.org/866603 + https://bugs.debian.org/1030846 for details. We _might_ need to check whether we're having e2fsprogs >=1.47.0-1 and then disable the feature when installing a release older than bookworm. :(

**Comment by mika** [comment]
Same for `orphan_file`, see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1031325#20

**Comment by zeha** [comment]
> We might need to check whether we're having e2fsprogs >=1.47.0-1 and then disable the feature when installing a release older than bookworm.

Wouldn't always disabling the new feature when installing <= bookworm work, i.e. dont do the version check?

**Comment by mika** [comment]
> Wouldn't always disabling the new feature when installing <= bookworm work, i.e. dont do the version check?

Yeah good idea! Didn't check though whether older e2fsprogs not being aware of this newer feature would complain when being invoked with ` -O ^metadata_csum_seed`, but if that works it would clearly simplify our live :) thx!

**Comment by mika** [comment]
Yeah so if e2fsprogs is older than v1.43 it fails:

```
root@grml ~ # mkfs.ext4 -O '^metadata_csum_seed' /dev/sda1
mke2fs 1.42.13 (17-May-2015)
/dev/sda1 contains a ext4 file system
        created on Mon Feb 20 07:24:41 2023
Proceed anyway? (y,n) y
Invalid filesystem option set: ^metadata_csum_seed
```

**Comment by zeha** [comment]
hmpf. that might be worthwhile feedback towards tytso.
