### ISSUE TITLE
--vmefi requires dependency on dosfstools

### ISSUE THREAD

**Issue by adrelanos** [grml/grml-debootstrap#225]
```
+ mkfs.fat -F32 -n EFI /dev/mapper/loop0p1
/usr/sbin/grml-debootstrap: line 1358: mkfs.fat: command not found
```

**Comment by adrelanos** [comment]
Should add a `Depends:` or `Recommends:` `dosfstools` to https://github.com/grml/grml-debootstrap/blob/master/debian/control?

**Comment by mika** [comment]
Thanks for asking, AFAICS dosfstools is small enough, available for all relevant architectures and shouldn't be a problem as a dependency, so let's make the user experience nice by adding it to `Depends`?
