### ISSUE TITLE
Debian stretch build failing due to missing busybox

### ISSUE THREAD

**Issue by adrelanos** [grml/grml-debootstrap#256]
For the purpose of landing

* https://github.com/grml/grml-debootstrap/pull/255
 
I noticed that the Debian stretch build is failing on CI due to missing busybox. This is happening due to:

* https://github.com/grml/grml-debootstrap/issues/240
* https://github.com/grml/grml-debootstrap/commit/2708f441697d1b9cd0443b433478ff222bac8a6d

I would speculate that #255 makes this issue visible and that the issue already existed after above commit removing the hardcoded busybox installation.

How do we resolve this? Options that come to mind:

* A) Drop Debian stretch support.
* B) Install busybox only for Debian stretch builds somehow by handling this case in the scripts.
* C) Re-add stretch to packages (and packages-arm64?) file.

**Comment by mika** [comment]
I've prepared something at https://github.com/grml/grml-debootstrap/pull/261 which should be as little intrusive as possible, IMO
