### ISSUE TITLE
How to deal with conflict between `cryptsetup-initramfs` and `dracut` in chroot script?

### ISSUE THREAD

**Issue by paulmenzel** [grml/grml-debootstrap#260]
I am using grml-debootstrap to install Debian on a LUKS encrypted root partition. Until now I have used initramfs to generate the initrd, and a chroot script installs `cryptsetup-initramfs`:

https://github.molgen.mpg.de/pmenzel/grml-debootstrap-config/blob/c15d864de3ac52568506ffc6adae42832d202255/chroot-scripts/01-update-packages.sh#L3-L4

Now when choosing dracut as initrd generator, this fails, as the chroot script unconditionally installs the package, basically removing dracut.

How should this be handled? Do I need to add checks into the chroot script to see which package is installed?

**Comment by mika** [comment]
Which grml-debootstrap version are you using, latest v0.105 one?

**Comment by paulmenzel** [comment]
Unfortunately, I did not use the latest one, but in a hurry the USB storage medium I had laying around.

    grml64-full_sid build4325 - Release Codename autobuild-build4325 [2023-10-30]

**Comment by paulmenzel** [comment]
I guess, I need to use the variable `INITRD_GENERATOR` in my custom chroot scripts.

**Comment by mika** [comment]
@paulmenzel please consider giving version >=0.105 a try, @adrelanos made some great improvements in the last version that might also be useful for your use case

**Comment by paulmenzel** [comment]
Thank you. I am going to do that, when time permits. Until then, I am closing the issue.
