### ISSUE TITLE
hard drive serial of build machine leaks into image in /boot/grub/device.map

### ISSUE THREAD

**Issue by adrelanos** [grml/grml-debootstrap#27]
inside a booted VM, created by grml-debootstrap:

```
cat /boot/grub/device.map
```

```
(hd0)	/dev/disk/by-id/ata-VBOX_HARDDISK_VB3680cb3a-83f0b2f8
```

-----

on my build machine that was used to create the image:
```
sudo hdparm -i /dev/sda | grep SerialNo
```
```
 Model=VBOX HARDDISK, FwRev=1.0, SerialNo=VB3680cb3a-83f0b2f8
```

-----

on a different VBox machine:
```
sudo hdparm -i /dev/sda | grep SerialNo
```
```
 Model=VBOX HARDDISK, FwRev=1.0, SerialNo=VB00cebe4d-00d96c5a
```

-----

Conclusion:
hard drive serial of build machine leaks into image in `/boot/grub/device.map`

-----

I tested mounting the image, deleting `/boot/grub/device.map`, unmounted the image - system still bootable.

-----

What should we do? I think shipping the existing `/boot/grub/device.map` isn't helpful, since it will be erroneous once the image gets booted, it might even be counter productive.

Should we delete `/boot/grub/device.map` at the end of the build process?

Should we ship a fixed `/boot/grub/device.map`? Any idea how a valid one would look like?

**Comment by adrelanos** [comment]
Yes. Still no issues with that.

**Comment by mika** [comment]
Thanks for your feedback, Patrick!
