### ISSUE TITLE
Use mmdebstrap as default

### ISSUE THREAD

**Issue by zeha** [grml/grml-debootstrap#290]
Necessary for grml-small. And generally a good idea.

**Comment by zeha** [comment]
@mika wrote:

> I'm actually wondering whether we should drop cdebootstrap support, I never ever use that, I think it's worth dropping this?

Agree, we should probably drop cdebootstrap support. I think it's dead in Debian, too.

We should also considering dropping debootstrap support. Doing that will allow us being clear about the tool that will run, remove a config var, simplify the test matrix, etc. And IMO mmdebstrap is strictly the better tool - if available.

Doing that might mean killing support for running on `stretch`. Or we figure out what to do about `--no-check-gpg` for stretch's mmdebstrap.

**Comment by adrelanos** [comment]
Does debootstrap have better cross architecture build support?

Or qemu-debootstrap?

I think it's worth keeping support for changing debootstrap tool for 
future-proofness.

**Comment by adrelanos** [comment]
Switching the default however seems nice.

**Comment by zeha** [comment]
> Does debootstrap have better cross architecture build support?
> Or qemu-debootstrap?

Even if they do, grml-debootstrap has IIRC no cross support.

**Comment by adrelanos** [comment]
grml-debootstrap has cross build support. Building ARM64 (on AMD64) was implemented here:

* https://github.com/grml/grml-debootstrap/issues/169
* https://github.com/grml/grml-debootstrap/pull/191

**Comment by zeha** [comment]
> grml-debootstrap has cross build support. Building ARM64 (on AMD64) was implemented here:
> 
> * [ARM support #169](https://github.com/grml/grml-debootstrap/issues/169)
> * [Initial arm64 support #191](https://github.com/grml/grml-debootstrap/pull/191)

Right. Then we should also run CI for that.
