### ISSUE TITLE
Git HEAD: Not mounting /dev/pts?

### ISSUE THREAD

**Issue by hartwork** [grml/grml-debootstrap#39]
During execution I noticed this line:
```
E: Can not write log (Is /dev/pts mounted?) - posix_openpt (2: No such file or directory)
```
Are you not mounting `/dev/pts` on purpose?

**Comment by hartwork** [comment]
I guess I'd need `try_umount` from pull request #50 to make a pull request for this one, first.
So I'll wait for comments on #50 for now.

**Comment by hartwork** [comment]
It seems I get the
```
Can not write log, openpty() failed (/dev/pts not mounted?)
```
despite a bind mount of /dev/pts into the chroot (set up by my pre-script). So just mounting that does not seem to fix the issue.

**Comment by mika** [comment]
Merged PR https://github.com/grml/grml-debootstrap/pull/74 - thanks.
