### ISSUE TITLE
Git HEAD: Claims to be the version installed system-wide (rather than the version in Git)

### ISSUE THREAD

**Issue by hartwork** [grml/grml-debootstrap#55]
Rather than obtaining its version from `debian/changelog`, grml-debootstrap currently introduces itself to the user as the version installed system-wide, while being potentially different code.

How the current code works:
```
$ fgrep -w VERSION grml-debootstrap
VERSION="$(dpkg-query --show --showformat='${Version}' "$PN")"
VERSION="${VERSION:-unknown}"
  einfo "$PN - version $VERSION"
   einfo "$PN [${VERSION}] - Please recheck configuration before execution:"
```

An idea, for how it could work instead:
* Check for a folder `"$(dirname $(which "$0")")/.git"`
* If found, ask for `dpkg-parsechangelog | sed -e '/^Version: / !d' -e 's|^Version: ||'`
* Else, use `dpkg-query --show --showformat='${Version}' "grml-debootstrap"` as done at the moment

What do you think?

**Comment by mika** [comment]
Fixed thanks to your PR, closing.
