### ISSUE TITLE
Git HEAD: Please make grml-debootstrap more friendly to install on non-Debian distributions

### ISSUE THREAD

**Issue by hartwork** [grml/grml-debootstrap#57]
# Background
Please make grml-debootstrap more friendly to build and install on non-Debian distributions. For instance, both Fedora and Gentoo do have all dependencies (including debootstrap) and could use a grml-debootstrap package.

# Changes needed
## ./Makefile
* Move `/usr/share/xml/docbook/stylesheet/nwalsh/manpages/docbook.xsl` to a variable so that it can be overridden using `make DOCBOOK_XML=... all` or so
* Move the steps from `debian/rules` targets `install` (and in part `binary-indep`) to a new target `install` in the master Makefile:
 * `dh_installdirs ...`
 * `install -m ... debian/grml-debootstrap/...`
 * `dh_installdocs TODO THANKS`
 * `dh_installman grml-debootstrap.8`
 * (if built, maybe install the sexy HTML documentation, too)

## ./grml-deboostrap
* Replace hardcoded `grub-mkimage` by something customizable. In some distros it is called `grub2-mkimage`.

**Comment by mika** [comment]
Good point, we should definitely do that, this would also allows us to use the minimal debian/rules approach.

**Comment by hartwork** [comment]
Many thanks. My Gentoo ebuild got a lo simpler from this, compare
* [grml-debootstrap-0.70.ebuild](https://gitweb.gentoo.org/proj/betagarden.git/tree/dev-util/grml-debootstrap/grml-debootstrap-0.70.ebuild) to
* [grml-debootstrap-0.70_p20150605.ebuild](https://gitweb.gentoo.org/proj/betagarden.git/tree/dev-util/grml-debootstrap/grml-debootstrap-0.70_p20150605.ebuild)

if curious.

I still need to patch "grub-mkimage" into "grub2-mkimage". That's the only thing left.

**Comment by mika** [comment]
Thanks for sharing the ebuild, I'm taking care of `config` file license to match GPL-2+ (wasn't aware of that).

I'm confused by the grub2-mkimage issue, the grub-mkimage binary is invoked from **inside** the installed system, and it's always called grub-mkimage in Debian/Ubuntu AFAICT. What's the problem you're facing here? (If there's a good reason why it's needed something like http://paste.grml.org/hidden/c6607573 should do the job.)

**Comment by hartwork** [comment]
My apology. That patching just turned out to be a leftover of my earlier mis-belief that grub-mkimage of the host system would be used rather than from inside the (Debian) chroot (similar to #72 and #83). So it's a bug in the ebuild which I have just fixed.

**Comment by mika** [comment]
Jey, so we're good. :) Is there any web page/ressource regarding the availability of grml-debootstrap within Gentoo we could officially point people to? Do you have any plans to move grml-debootstrap from betagarden to an official portage/ebuild (or how that's called in Gentoo speak)?

**Comment by hartwork** [comment]
Before official,
```
sudo layman -a betagarden
sudo emerge -av dev-util/grml-debootstrap
```
would work. To make it official as-is, `sys-apps/debian-archive-keyring` would need moving too, depending on ones view about it. It's actually sort of needed for debootstrap too already and there was some related ticket, I just haven't gotten around to it, yet.

**Comment by mika** [comment]
Ok cool - thanks! I'd appreciate if you could ping me if `grml-debootstrap` should make its way to official™!
