### ISSUE TITLE
Git HEAD: Lack of user input escaping / use of $!`"\ in passwords

### ISSUE THREAD

**Issue by hartwork** [grml/grml-debootstrap#58]
# Introduction
I am feeding generated passwords to grml-debootstrap's `--password` parameter. Passwords including special characters. I noticed an error
```
unexpected EOF while looking for matching ``'
```
flying by the other day  and traced it back to the occurrance of a single backtick in the generated password. That made me have a closer look. I found that when grml-debootstrap is writing file `/var/cache/grml-debootstrap/variables_...` for later evaluation, it is not escaping variable content (i.e. user input):
```
:
[ -n "$ROOTPASSWORD" ] && echo "ROOTPASSWORD=\"$ROOTPASSWORD\"" >> "$CHROOT_VARIABLES"
[ -n "$SCRIPTS" ] && echo "SCRIPTS=\"$SCRIPTS\"" >> "$CHROOT_VARIABLES"
:
```

# Problem in detail
To see a troublesome password in action try this:
```
# ROOTPASSWORD='foo`bar'

# echo "${ROOTPASSWORD}"
foo`bar

# eval "ROOTPASSWORD=\"$ROOTPASSWORD\""
bash: unexpected EOF while looking for matching ``'
bash: syntax error: unexpected end of file
```
With the current code, I expect (at least) these characters to be trouble:
* `$` dollar
* `!` exclamation mark
* backtick
* `"` double quote
* `\` backslash

# About a fix
The fix I have in mind is made of two parts:
* Switch to single ticks which changes the set of troublesome characters to just `'` (single quote)
* escape all single quotes in the variable content properly (details follow)

The first alone would make
```
echo "ROOTPASSWORD='$ROOTPASSWORD'"
```
which is broken:
```
# ROOTPASSWORD=single\'single

# eval "ROOTPASSWORD='$ROOTPASSWORD'"
bash: unexpected EOF while looking for matching `''
bash: syntax error: unexpected end of file
```
For escaping, note that double quotes can be escaped in double quoted string ..
```
# eval 'echo "\""'
"
```
but single quotes cannot (.. be escaped in a single quoted string):
```
# eval "echo '\''"
bash: unexpected EOF while looking for matching `''
bash: syntax error: unexpected end of file
```
I believe the proper way to escape (single quotes inside a single quoted string) is to replace `'` by `'\''` (single quote, backslash, single quote, single quote), i.e. ending the open quote, write an escape single quote, and open a new quoted string.
Here is a demo using Bash's own substitutions (i.e. with no forking):
```
# APOS=zero\'one\\\'two\\\\\'three

# echo $APOS
zero'one\'two\\'three

# eval "echo '${APOS//\'/\'\\\'\'}'"
zero'one\'two\\'three
```
I am happy to help out with a patch if you agree this is the way to go.

Best, Sebastian

**Comment by mika** [comment]
Fixed thanks to your, PR!
