### ISSUE TITLE
security issue - use full fingerprint instead of short gpg ids

### ISSUE THREAD

**Issue by adrelanos** [grml/grml-debootstrap#64]
Code in question:
https://github.com/grml/grml-debootstrap/blob/master/chroot-script#L157
```
# make sure we have the keys available for aptitude
gpg --keyserver subkeys.pgp.net --recv-keys F61E2E7CECDEA787
gpg --export F61E2E7CECDEA787 | apt-key add - || true # not yet sure
# why it's necessary, sometimes we get an error even though it works [mika]
```

Short gpg id's are bad:
http://www.asheesh.org/note/debian/short-key-ids-are-bad-news.html

To make it worse, there is another bug `gpg --recv-keys` truncates requests:
http://bugs.g10code.com/gnupg/issue1340

Better use the full 40 digits everywhere.

**Comment by mika** [comment]
But we *are* already using a long version, the short would be ECDEA787 while we use F61E2E7CECDEA787 instead. I can't get any further information for a "longer" key from `gpg --with-colons --list-keys 0xECDEA787` either, am I missing something?

**Comment by adrelanos** [comment]
You can view the full key fingerprint by running.

```
gpg --fingerprint F61E2E7CECDEA787
```

Current you got:
```
gpg --keyserver subkeys.pgp.net --recv-keys F61E2E7CECDEA787
gpg --export F61E2E7CECDEA787 | apt-key add - || true # not yet sure
```

Suggested:
```
gpg --keyserver subkeys.pgp.net --recv-keys 709BCE51568573EBC160E590F61E2E7CECDEA787
gpg --export 709BCE51568573EBC160E590F61E2E7CECDEA787 | apt-key add - || true # not yet sure
```

**Comment by mika** [comment]
Ah I see, thanks for clarification, just took take care of it!
