### ISSUE TITLE
Git HEAD: Does not respect GRUB_DISABLE_LINUX_UUID=true

### ISSUE THREAD

**Issue by hartwork** [grml/grml-debootstrap#65]
Hi!
The current code of grml-debootstrap patches `grub.cfg` for some distributions, including wheezy:
```
  case "$RELEASE" in
    lenny|squeeze|wheezy)
      einfo "Adjusting grub.cfg for successful boot sequence."
      sed -i "s;root=[^ ]\+;root=UUID=$TARGET_UUID;" "${MNTPOINT}"/boot/grub/grub.cfg
      ;;
  esac
```
Now with booting a wheezy PV Xen using pygrub, I write
```
GRUB_DISABLE_LINUX_UUID=true
```
into `/etc/default/grub` and run update-grub afterwards as part of a chroot schript, since pygrub (of wheezy, too) does not support UUID magic, unfortunately.

Now the problem is that grml-debootstrap weaves UUIDs back in by itself, even if previous `update-grub` pruduced results considered sane with respect to that scenario.

So for that patching code, it would be cool to have
* support for `GRUB_DISABLE_LINUX_UUID=true` and/or
* a switch to disable patching of `grub.cfg`

**Comment by adrelanos** [comment]
Looking at https://github.com/grml/grml-debootstrap/commit/a8c2e5f14dc2a1892c99acfc54a32efe5748b07c...

```
if grep -q '^GRUB_DISABLE_LINUX_UUID=true' "${MNTPOINT}"/etc/default/grub 2>/dev/null ; then
```

* This would not cover cases, which which someone is using `GRUB_DISABLE_LINUX_UUID="true"` or `GRUB_DISABLE_LINUX_UUID='true'`.
* This would not cover cases in which someone dropped a snippet in `/etc/default/grub.d`. For 100% correctness, you would have to mimic what `/usr/sbin/grub-mkconfig` (sh script) is doing. I.e. `source`ing `/etc/default/grub` file followed by `/etc/default/grub.d` folder in lexical order.
* Not source `source`ing that folder as `/usr/sbin/grub-mkconfig` is worth it though.

-----

```
  case "$RELEASE" in
    lenny|squeeze|wheezy)
      if grep -q '^GRUB_DISABLE_LINUX_UUID=true' "${MNTPOINT}"/etc/default/grub 2>/dev/null ; then
        ewarn "GRUB_DISABLE_LINUX_UUID is set to true in /etc/default/grub, not adjusting root= in grub.cfg."
        ewarn "Please note that your system might NOT be able to properly boot."
      else
        einfo "Adjusting grub.cfg for successful boot sequence."
        sed -i "s;root=[^ ]\+;root=UUID=$TARGET_UUID;" "${MNTPOINT}"/boot/grub/grub.cfg
      fi
      ;;
  esac
```

Inquiry, that means for releases >= `jessie` it is okay to always run `sed -i "s;root=[^ ]\+;root=UUID=$TARGET_UUID;" "${MNTPOINT}"/boot/grub/grub.cfg`? It does not need that `if grep` check?

**Comment by mika** [comment]
* Patrick Schleizer [Thu Jun 04, 2015 at 05:34:47AM -0700]:
> Looking at https://github.com/grml/grml-debootstrap/commit/a8c2e5f14dc2a1892c99acfc54a32efe5748b07c...

> ```
> if grep -q '^GRUB_DISABLE_LINUX_UUID=true' "${MNTPOINT}"/etc/default/grub 2>/dev/null ; then
> ```

> * This would not cover cases, which which someone is using `GRUB_DISABLE_LINUX_UUID="true"` or `GRUB_DISABLE_LINUX_UUID='true'`.

Thanks for catching this, fixed through new commit d5528b0241abf8da1700e02bf9b463ca47495ea8


> * This would not cover cases in which someone dropped a snippet in `/etc/default/grub.d`. For 100% correctness, you would have to mimic what `/usr/sbin/grub-mkconfig` (sh script) is doing. I.e. `source`ing `/etc/default/grub` file followed by `/etc/default/grub.d` folder in lexical order.
> * Not source `source`ing that folder as `/usr/sbin/grub-mkconfig` is worth it though.

Uh, I've no idea how to properly and safely check for /etc/default/grub.d use case.
Glady accept any patches for that, otherwise it will stay as it is
(and probably be safe enough for 99% of the use cases).

> -----

> ```
>   case "$RELEASE" in
>     lenny|squeeze|wheezy)
>       if grep -q '^GRUB_DISABLE_LINUX_UUID=true' "${MNTPOINT}"/etc/default/grub 2>/dev/null ; then
>         ewarn "GRUB_DISABLE_LINUX_UUID is set to true in /etc/default/grub, not adjusting root= in grub.cfg."
>         ewarn "Please note that your system might NOT be able to properly boot."
>       else
>         einfo "Adjusting grub.cfg for successful boot sequence."
>         sed -i "s;root=[^ ]\+;root=UUID=$TARGET_UUID;" "${MNTPOINT}"/boot/grub/grub.cfg
>       fi
>       ;;
>   esac
> ```

> Inquiry, that means for releases >= `jessie` it is okay to always run `sed -i "s;root=[^ ]\+;root=UUID=$TARGET_UUID;" "${MNTPOINT}"/boot/grub/grub.cfg`? It does not need that `if grep` check?

For releases other than lenny|squeeze|wheezy the if/else/sed never
is reached at all.

**Comment by adrelanos** [comment]
> For releases other than lenny|squeeze|wheezy the if/else/sed never is reached at all.

Yes. 

These releases work fine without the sed command?

**Comment by mika** [comment]
> These releases work fine without the sed command?

Yes
