### ISSUE TITLE
grub root=/dev/mapper/loop0p1

### ISSUE THREAD

**Issue by koppi** [grml/grml-debootstrap#87]
I'm running grml-debootstrap as follows:

```bash
RELEASE=jessie
        
sudo http_proxy=http://localhost:3142/ \
     grml-debootstrap \
     --release $RELEASE \
     --hostname machinekit \
     --bootappend "xeno_hal.smi=1 lapic=notscdeadline hpet=disable i915.i915_enable_rc6=0 i915.powersave=0 intel_idle.max_cstate=1 processor.max_cstate=1 isolcpus=1 idle=poll" \
     --mirror http://ftp.de.debian.org/debian \
     --vmfile --target machinekit-$RELEASE.img \
     --vmsize 4G \
     --scripts $RELEASE/scripts \
     --chroot-scripts $RELEASE/chroot-scripts \
     --force \
     --password mk \
     --nokernel \
     --defaultinterfaces
```
When I boot the image in qemu, there is ```root=/dev/mapper/loop0p1``` and the kernel does not boot
![20150530-001](https://cloud.githubusercontent.com/assets/9458631/7897027/33cd4716-06cd-11e5-9c49-83c34923e561.png)

When I set ```root=/dev/sda1``` during grub boot, the kernel boots, when I run ```sudo update-grub``` inside the qemu instance, the entry becomes ```root=UUID=...``` and the image boots.

**Comment by koppi** [comment]
What needs to be changed, that grml-debootstrap generates an entry with ```root=UUID=...```?

**Comment by koppi** [comment]
```bash
$ dpkg -l | grep grml-debootstrap
ii  grml-debootstrap                                            0.69                                       all          wrapper around debootstrap for installing pure Debian
```

**Comment by mika** [comment]
Wanted to reproduce this, but sadly ran into another GRUB bug (unsure whether this a known one yet): http://michael-prokop.at/screeni/screenshot.2015-06-03T17:56:45.png ->

````
source /boot/grub/grub.cfg
error: file `/boot/grub/fonts/unicode.pf2' not found.
error: no suitable video mode found.
grub> ls /boot/grub/
unicode.pf2 i386-pc/ grub.cfg
````

**Comment by mika** [comment]
The mentioned unicode.pf issue is https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=787685

I'm not able to reproduce this bug with grml-debootstrap v0.70.0 executing:

````
% sudo grml-debootstrap \               
     --release jessie \
     --hostname grml \
     --mirror http://ftp.de.debian.org/debian \
     --vmfile --target jessie.img \
     --vmsize 4G \
     --password grml \
     --defaultinterfaces
````

The resulting grub.cfg uses root=UUID as expected (since Debian/jessie's GRUB used root=UUID by default, also see GRUB_DISABLE_LINUX_UUID=true in /etc/default/grub).

Either it's related to a) any of your scripts (do you modify grub files? does the non-default kernel package you seem to be using touch anything?), b) the bootappend option (which I don't think should trigger this behaviour), c) something between grml-debootstrap 0.69 and 0.70 (which I don't see either) or d) specific to your environment (I'm executing it on a Debian/jessie system).

Can you please rerun my cmdline from above and let me know whether the resulting jessie.img works for you?

**Comment by koppi** [comment]
```bash
sudo grml-debootstrap --release jessie --hostname grml --mirror http://ftp.de.debian.org/debian --vmfile --target jessie.img --vmsize 4G --password grml --defaultinterfaces
```
I just ran the command line above, what I see in the boot process I captured in the following screenshot:
![20150628-002](https://cloud.githubusercontent.com/assets/9458631/8397482/c3a043aa-1dcc-11e5-85bb-75b8826f51a1.png)

```bash
$ dpkg -l | grep grml-debootstrap
ii  grml-debootstrap                                            0.72                                       all          wrapper around debootstrap for installing pure Debian
```
Ubuntu here:
```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.04
Release:	15.04
Codename:	vivid
```

**Comment by koppi** [comment]
I just ran the same command on Debian / Jessie and the root=UUID entry is set correct there, so the issue seems related to Ubuntu. I'm closing this, as I now run this from Debian/Jessie and I have no time to investigate what's different to Jessie in Vivid.

**Comment by hex2a** [comment]
I encountered this issue with a debian wheezy host when provisioning a jessie VM on a LV, see #96
