### ISSUE TITLE
Please support --vm (with and) without installing Grub (for pygrub Xen): Add --no-grub?

### ISSUE THREAD

**Issue by hartwork** [grml/grml-debootstrap#88]
The current stages order of
- ..
- `execute_pre_scripts`
- `chrootscript`
- `execute_post_scripts`
- ..
- `finalize_vm` -- installation of GRUB -- no script stages after
- ..

require a wrapper around grml-debootstrap adding something like a post-post script execution stage for people who want to uninstall GRUB, be it for
- a) installing a different bootloader or
- b) no bootloader at all.

including need to set up and tear down a full chroot with mounts once again for `apt-get remove ...`. Not too much fun.

(My case is with pygrub: no bootloader but a manual GRUB config file that (frustratingly limited parser of) pygrub is analyzing to boot a PV Xen guest. Having GRUB installed in the guest means that any call to update-grub later can turn the Xen guest unbootable since grub.cfg turns into something that pygrub cannot parse, rather easily. So to not have GRUB around when bootstrapping is done is what I am aiming for.)

Instead of installing and then uninstalling GRUB again, not installing it in the first place would be cool and save the ugly stunts needed on user end for uninstalling GRUB as of today.

What do you think?

**Comment by mika** [comment]
Agreed and understood. Actually `finalize_vm()` is just about installation and setup of GRUB, so assuming you could disable `finalize_vm` execution you could do everything via `execute_post_scripts`?

**Comment by mika** [comment]
Ah, missed the `--no-grub` in the subject, so yeah, if that's all what you need (don't touch grub related files + don't install grub) then this should be easy to do.

**Comment by hartwork** [comment]
Cool.

I added "--no-grub" to the title in case GRUB is installed even without --grub for a default. I'd have to re-check.

**Comment by suntong** [comment]
Saw that feature already in place during my latest install. 

Can this issue be closed now?

**Comment by mika** [comment]
@suntong thanks for noticing, since commit 0b1b798eb35cfc23f12819b55a11fff507b1e190 and with `GRUB_INSTALL='no'` it indeed should be possible to skip grub handling within VMs. Closing this hereby, if anything isn't working as needed or if anything should be improved please let me/us know. Thanks everyone.
