### ISSUE TITLE
Creating partition fails depending on prior block device content

### ISSUE THREAD

**Issue by hartwork** [grml/grml-debootstrap#90]
I am passing LVM volumes for installation to _grml-debootstrap_. Previously, these LVM volumes were created using calls to lvcreate containing `--zero n`. It turned out, that triggers a bug in _grml-debootstrap_.
With `--zero n`, the new LVM volume may contains bytes from the past, not just in general, but in the first 1024 bytes, too. In my case, they contained fractions of a GPT partition table.

The related code in _grml-debootstrap_ is this:
```
echo 4 66 | /usr/share/grml-debootstrap/bootgrub.mksh -A | dd of="$TARGET" conv=notrunc
dd if=/dev/zero bs=1 conv=notrunc count=64 seek=446 of="$TARGET"
if [ "$FIXED_DISK_IDENTIFIERS" = "yes" ] ; then
  [..]
fi
parted -s "${TARGET}" 'mkpart primary ext4 2M -1'

[..]

DEVINFO=$(kpartx -asv "$TARGET") # 'add map loop1p1 (253:0): 0 6289408 linear /dev/loop1 2048'
if [ -z "${DEVINFO}" ] ; then
  eerror "Error setting up loopback device." ; eend 1
  bailout 1
fi
```
`bootgrub.mksh` does some magic, part of that is reverted to zero, a new partition is created, and the partition block device is activated. Of those steps, the first two are not waterproof.
For certain prior content, parted will error out saying
```
Warning: /dev/foo contains GPT signatures, indicating that it has a GPT table.  However, it does not have a valid fake msdos partition table, as it should.  Perhaps it was corrupted -- possibly by a program that doesn't understand GPT partition tables.  Or perhaps you deleted the GPT table, and are now using an msdos partition table.  Is this a GPT partition table?
Error: Invalid argument during seek for read on /dev/foo
```
but the return code is not checked so execution fails later, when kpartx is called and its output is inspected. kpartx itself wrote to stderr:
```
  Warning: Disk has a valid GPT signature but invalid PMBR.
  Assuming this disk is *not* a GPT disk anymore.
  Use gpt kernel option to override.  Use GNU Parted to correct disk.
```
The whole output of _grml-debootstrap_ is this
```
 * Reading specified config file /etc/.................
 * grml-debootstrap [0.69.1] - Please recheck configuration before execution:

   Target:          /dev/foo
   Install grub:    yes
   Using release:   jessie
   Using hostname:  foo
   Using mirror:    ...........
   Using arch:      amd64
   Deploying as Virtual Machine.

   Important! Continuing will delete all data from /dev/foo!
 * Skip user acknowledgement as requested via --force option.
0 @0x168: 63 @4 (0x4)
 - 0x168: 32 (0x20) @ 4 (0x4)
 - 0x16A: 31 (0x1F) @ 36 (0x24)
using 2 blocks, 4 bytes (146 free)
using sectors of 2^9 = 512 bytes
1+0 records in
1+0 records out
512 bytes (512 B) copied, 0.0350562 s, 14.6 kB/s
64+0 records in
64+0 records out
64 bytes (64 B) copied, 0.00644675 s, 9.9 kB/s
Warning: /dev/dm-3 contains GPT signatures, indicating that it has a GPT table.  However, it does not have a valid fake msdos partition table, as it should.  Perhaps it was corrupted -- possibly by a program that doesn't understand GPT partition tables.  Or perhaps you deleted the GPT table, and are now using an msdos partition table.  Is this a GPT partition table?
Error: Invalid argument during seek for read on /dev/dm-3
  Warning: Disk has a valid GPT signature but invalid PMBR.
  Assuming this disk is *not* a GPT disk anymore.
  Use gpt kernel option to override.  Use GNU Parted to correct disk.
 * Error setting up loopback device.
 -> Failed (rc=1)
 * Removing /var/cache/grml-debootstrap/stages_foo
 * Removing loopback mount of file /dev/foo.
  Warning: Disk has a valid GPT signature but invalid PMBR.
  Assuming this disk is *not* a GPT disk anymore.
  Use gpt kernel option to override.  Use GNU Parted to correct disk.
```
(While saying 0.69.1, the issue is not specific to that version.)

A disk `trouble2g` triggering that trouble can be created easily using
```
truncate --size $((2 * 1024**3 + 1024**2)) trouble2g
parted -s trouble2g mklabel gpt
truncate --size $((2 * 1024**3)) trouble2g
```
The idea is to produce GPT leftovers that point to a backup (at the last 512 bytes) _outside_ of the device. That makes _parted_ fail with "Invalid argument during seek".

Using bzip2 and base64, I can actually paste the whole disk inline in just 2213 bytes:
```
$ cat trouble2g.bz2.base64
QlpoOTFBWSZTWd5UiVUAAATf+/jAVAIAlGMg1hQAgAACUQAIEAAbQgIQoQIBAAmgAJKM2oAAA0A0
00AxqAilJiaAGgAA0AaNPkYSW5Na+igAqqJVOu3gSKgAqqJPGyEFAVVEkgIgBAFVRLI9QGAjQhvk
947gspSH70ObI6F6/TKBAegPPZkqSL4rNILhFABVUT9Z1mly/zFBWSZTWQ4J4t8BX45AAMAAAAgg
ADCATUZCoCWpCoCXMUFZJlNZDgni3wFfjkAAwAAACCAAMIBNRkKgJakKgJcxQVkmU1kOCeLfAV+O
QADAAAAIIAAwgE1GQqAlqQqAlzFBWSZTWQ4J4t8BX45AAMAAAAggADCATUZCoCWpCoCXMUFZJlNZ
Dgni3wFfjkAAwAAACCAAMIBNRkKgJakKgJcxQVkmU1kOCeLfAV+OQADAAAAIIAAwgE1GQqAlqQqA
lzFBWSZTWQ4J4t8BX45AAMAAAAggADCATUZCoCWpCoCXMUFZJlNZDgni3wFfjkAAwAAACCAAMIBN
RkKgJakKgJcxQVkmU1kOCeLfAV+OQADAAAAIIAAwgE1GQqAlqQqAlzFBWSZTWQ4J4t8BX45AAMAA
AAggADCATUZCoCWpCoCXMUFZJlNZDgni3wFfjkAAwAAACCAAMIBNRkKgJakKgJcxQVkmU1kOCeLf
AV+OQADAAAAIIAAwgE1GQqAlqQqAlzFBWSZTWQ4J4t8BX45AAMAAAAggADCATUZCoCWpCoCXMUFZ
JlNZDgni3wFfjkAAwAAACCAAMIBNRkKgJakKgJcxQVkmU1kOCeLfAV+OQADAAAAIIAAwgE1GQqAl
qQqAlzFBWSZTWQ4J4t8BX45AAMAAAAggADCATUZCoCWpCoCXMUFZJlNZDgni3wFfjkAAwAAACCAA
MIBNRkKgJakKgJcxQVkmU1kOCeLfAV+OQADAAAAIIAAwgE1GQqAlqQqAlzFBWSZTWQ4J4t8BX45A
AMAAAAggADCATUZCoCWpCoCXMUFZJlNZDgni3wFfjkAAwAAACCAAMIBNRkKgJakKgJcxQVkmU1kO
CeLfAV+OQADAAAAIIAAwgE1GQqAlqQqAlzFBWSZTWQ4J4t8BX45AAMAAAAggADCATUZCoCWpCoCX
MUFZJlNZDgni3wFfjkAAwAAACCAAMIBNRkKgJakKgJcxQVkmU1kOCeLfAV+OQADAAAAIIAAwgE1G
QqAlqQqAlzFBWSZTWQ4J4t8BX45AAMAAAAggADCATUZCoCWpCoCXMUFZJlNZDgni3wFfjkAAwAAA
CCAAMIBNRkKgJakKgJcxQVkmU1kOCeLfAV+OQADAAAAIIAAwgE1GQqAlqQqAlzFBWSZTWQ4J4t8B
X45AAMAAAAggADCATUZCoCWpCoCXMUFZJlNZDgni3wFfjkAAwAAACCAAMIBNRkKgJakKgJcxQVkm
U1kOCeLfAV+OQADAAAAIIAAwgE1GQqAlqQqAlzFBWSZTWQ4J4t8BX45AAMAAAAggADCATUZCoCWp
CoCXMUFZJlNZDgni3wFfjkAAwAAACCAAMIBNRkKgJakKgJcxQVkmU1kOCeLfAV+OQADAAAAIIAAw
gE1GQqAlqQqAlzFBWSZTWQ4J4t8BX45AAMAAAAggADCATUZCoCWpCoCXMUFZJlNZDgni3wFfjkAA
wAAACCAAMIBNRkKgJakKgJcxQVkmU1kOCeLfAV+OQADAAAAIIAAwgE1GQqAlqQqAlzFBWSZTWQ4J
4t8BX45AAMAAAAggADCATUZCoCWpCoCXMUFZJlNZDgni3wFfjkAAwAAACCAAMIBNRkKgJakKgJcx
QVkmU1kOCeLfAV+OQADAAAAIIAAwgE1GQqAlqQqAlzFBWSZTWQ4J4t8BX45AAMAAAAggADCATUZC
oCWpCoCXMUFZJlNZDgni3wFfjkAAwAAACCAAMIBNRkKgJakKgJcxQVkmU1kOCeLfAV+OQADAAAAI
IAAwgE1GQqAlqQqAlzFBWSZTWQ4J4t8BX45AAMAAAAggADCATUZCoCWpCoCXMUFZJlNZDgni3wFf
jkAAwAAACCAAMIBNRkKgJakKgJcxQVkmU1kOCeLfAV+OQADAAAAIIAAwgE1GQqAlqQqAlzFBWSZT
WWJrqtsBFLBgAMAAAAEACCAAMMwFKaYFIkNiCkSHi7kinChIMdFvrQA=
```
Unpacked, expect to see this:
```
# base64 -d < trouble2g.bz2.base64 | bzip2 -d | hexdump -C
00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
000001c0  01 00 ee fe ff ff 01 00  00 00 ff 07 40 00 00 00  |............@...|
000001d0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
000001f0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 55 aa  |..............U.|
00000200  45 46 49 20 50 41 52 54  00 00 01 00 5c 00 00 00  |EFI PART....\...|
00000210  7d ad 67 e5 00 00 00 00  01 00 00 00 00 00 00 00  |}.g.............|
00000220  ff 07 40 00 00 00 00 00  22 00 00 00 00 00 00 00  |..@.....".......|
00000230  de 07 40 00 00 00 00 00  d9 82 ae 93 08 3c 37 4f  |..@..........<7O|
00000240  b0 24 d7 3a 9a b5 fe 5a  02 00 00 00 00 00 00 00  |.$.:...Z........|
00000250  80 00 00 00 80 00 00 00  86 d2 54 ab 00 00 00 00  |..........T.....|
00000260  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
80000000
```
To fix the issue I suggest to
* a) resolve `bootgrub.mksh` and use regular tools like _parted_ to create a clean partition table, or
* b) zero the first 1024 bytes and the last 512 bytes of the device before calling `bootgrub.mksh`, or
* c) both of these.

PS: I would be interested why `bootgrub.mksh` is currently used.

**Comment by hartwork** [comment]
Any news?

**Comment by mika** [comment]
Sorry4delay and thanks for detailed analysis.

> PS: I would be interested why bootgrub.mksh is currently used. 

To be able to install GRUB at all in the VM situation, without this hack it's not possible to get GRUB properly installed.

I talked to the author of bootgrub.mksh and he recommends that we should go for:

>     * b) zero the first 1024 bytes and the last 512 bytes of the device before calling bootgrub.mksh, 

So I guess that's what we should do about this issue, unless someone comes up with a way how to get rid of bootgrub.mksh usage.

**Comment by hartwork** [comment]
> To be able to install GRUB at all in the VM situation

What would that be? Which of those does parted not handle well?

**Comment by mika** [comment]
Just try executing grml-debootstrap with:

````
echo 4 66 | /usr/share/grml-debootstrap/bootgrub.mksh -A | dd of="$TARGET" conv=notrunc
````

disabled. Does this work for you?

**Comment by hartwork** [comment]
It would need to be replaced by something like
```
parted --script "$TARGET" mklabel msdos
```
of course.

**Comment by mika** [comment]
If you get that working I'd happily accept a patch. :)

**Comment by mika** [comment]
Thanks for the PR, this builds fine, though the resulting VM doesn't boot for me.
What I did:

````
% sudo grml-debootstrap --vmfile --vmsize 2g --verbose --hostname machine-1 \
--release jessie --target ./machine-1.hdd --password foo --nopackages --filesystem ext4 
```

Does this work for you with your patches applied?

**Comment by hartwork** [comment]
It seems you are right.

`parted -s "${TARGET}" 'set 1 boot on'` was missing in a way, but that alone does not fix the problem.

Bringing back the
```
dd if=/dev/zero bs=1 conv=notrunc count=64 seek=446 of="$TARGET"
```
line does not help, either.

I use parted and grub-_install_ elsewhere and the results boot just fine, so I believe it's the current dd'ing of grub-mkimage output that _alone_ does not result in bootable GRUB.

Any ideas how to proceed?

**Comment by mika** [comment]
No ideas how to get rid of `bootgrub.mksh` (I'm not aware of any projects being able to do what we provide with grml-debootstrap WRT that), though regarding the actual reported issue I think:

````
b) zero the first 1024 bytes and the last 512 bytes of the device before calling bootgrub.mksh, or
````

is what needs testing and integration.

**Comment by hartwork** [comment]
> (I'm not aware of any projects being able to do what we provide with grml-debootstrap WRT that)

I really wonder what `bootgrub.mksh` is actually doing.

**Comment by hartwork** [comment]
> Thanks for the PR, this builds fine, though the resulting VM doesn't boot for me.
> What I did:
>
> % sudo grml-debootstrap --vmfile --vmsize 2g --verbose --hostname machine-1 \
> --release jessie --target ./machine-1.hdd --password foo --nopackages --filesystem ext4 
> 
> Does this work for you with your patches applied?

@mika, I can offer a fix by now: With commit b1e8700edf71bdc59f9278b79b241510d081fafb added to #92 now, that very command now does result in a bootable image; all without `bootgrub.mksh` :smiley: Please check the commit message for details. I am happy to work on a pull request for #90, after.

**Comment by mika** [comment]
Wow, nice one! I've merged PR #92 just now after some testing, this definitely clarifies things. Thanks! I'd happily accept further patches/work on #90 :) :+1:

**Comment by hartwork** [comment]
It turns out that #92 fixes #90 as a side effect. We could still write zeros if you like but `parted ... mklabel ...` already ensures that subsequent `parted ... mkpart ...` succeeds.

I have written and attached a small script to demonstrate that matter. Use it like
```
# bash issue-90.sh.txt
```
and
```
# USE_BOOTGRUB_MKSH=true bash issue-90.sh.txt
```
to see it (1) fail with prior `bootstrap.mksh` and (2) succeed with `parted`. One must be on wheezy to see the failure, parted on jessie does not error out any more. Also, you will need to have `bootstrap.mksh` around. No sudo/root needed.

Please let me know how to proceed. Close oder write zeros anyway?


Attachments:
[issue-90.sh.txt](https://github.com/grml/grml-debootstrap/files/148414/issue-90.sh.txt)

**Comment by mika** [comment]
Nice investigation, thanks! So users on Debian/jessie and newer don't have the problem noted in #90 anymore? If so I'd say we consider this as resolved.

**Comment by hartwork** [comment]
Alright, closing.
