### ISSUE TITLE
/etc/hosts processing broken

### ISSUE THREAD

**Issue by hartwork** [grml/grml-debootstrap#94]
Hi!

A colleague of mine noticed that the current code to modify existing `/etc/hosts` files (https://github.com/grml/grml-debootstrap/blob/master/chroot-script#L430) does not work as intended because it expects spaces for a separator while `/etc/hosts` is separated by tabs, in practice. Please see my results for wheezy and jessie:

```
# cat /mnt/wheezy/etc/hosts
127.0.0.1       localhost
::1             localhost ip6-localhost ip6-loopback
fe00::0         ip6-localnet
ff00::0         ip6-mcastprefix
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters

# cat /mnt/jessie/etc/hosts 
127.0.0.1       localhost
::1             localhost ip6-localhost ip6-loopback
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters
```

So there are no traces of the actual hostname.

For completeness, my command line was:

```
for i in wheezy jessie ; do grml-debootstrap --vmfile --vmsize 2g --target $i.hdd --release $i --password .... --hostname debian$i --force ; done
```

Best, Sebastian

**Comment by hartwork** [comment]
Also, maybe the hostname should go before localhost rather than after?
How about this for a fix?:
```
- sed -i "s#127.0.0.1 .*#127.0.0.1       localhost  $HOSTNAME#" /etc/hosts
+ sed -i "s#127.0.0.1\([\t ]\+\).*#127.0.0.1\1$HOSTNAME  localhost#" /etc/hosts
```
It would support both spaces and tabs (and push localhost to the end).

**Comment by evgeni** [comment]
Why not

    sed -i "s#\(127.0.0.1\s\+\).*#\1$HOSTNAME  localhost#" /etc/hosts

(\s for all spaces, instead of \t and " ")

but other than that, yeah, why not.

@mika @formorer?

**Comment by hartwork** [comment]
No objections to `\s` from me, seems to work well.

**Comment by mika** [comment]
Sorry for late reply. I'm actually wondering whether we should modify /etc/hosts at all? Is there any need to put the $HOSTNAME into /etc/hosts for the default installation?

**Comment by sts** [comment]
IMHO putting the hostname in /etc/hosts doesn't make sense, as long as you are unable to supply a network interface and ip address.  $HOSTNAME usually shouldn't point to 127.0.0.0/8 but rather to the IP of the DNS record (or even of the interface which is used as default gateway uses).

For conistency trying to reach server01.grml.org should work the same from the local OS instance, as well from any other hosts.
